import React, { createContext, useContext, useState } from 'react';

type Language = 'en' | 'hi' | 'ru' | 'fa' | 'ar' | 'tr' | 'es' | 'pt' | 'id' | 'ur' | 'bn' | 'fr' | 'de' | 'it' | 'zh' | 'ja' | 'ko';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    home: 'Home',
    shop: 'Shop',
    menu: 'Menu',
    settings: 'Settings',
    my_uid: 'My UID',
    language: 'Language',
    contact_support: 'Contact Support',
    legal_info: 'Legal Information',
    terms_conditions: 'Terms & Conditions',
    privacy_policy: 'Privacy Policy',
    acceptable_use: 'Acceptable Use Policy',
    copied: 'Copied to clipboard!',
    close: 'Close',
    axn_balance: 'AXN Balance',
    user_account: 'User Account',
    active: 'Active',
    user_uid: 'User UID',
    account_localization: 'Account & Localization',
    support_legal: 'Support & Legal',
    app_language: 'App Language',
    invite_friends: 'Invite Friends',
    earn_commissions: 'Earn Commissions',
    watch_ads: 'Watch Ads',
    daily_reward: 'Daily Reward',
    mining_status: 'Mining Status',
    rank: 'Rank',
    total_axn: 'Total AXN',
    total_usd: 'Total USD',
    mining_power: 'Mining Power',
    earn: 'Earn',
    referrals: 'Referrals',
    invite_friends_earn: 'Invite friends and earn',
    referral_desc_prefix: '10% of their AXN and When your friend buys a plan you get',
    referral_desc_suffix: 'instantly',
    user_referred: 'User referred',
    successful: 'Successful',
    copy_link: 'Copy Link',
    total_axn_mined: 'Total AXN Mined',
    total_ton_earned: 'Total TON Earned',
    mined_axn: 'MINED AXN',
    upgrade: 'UPGRADE',
    claim: 'CLAIM',
    convert: 'Convert',
    promo: 'Promo',
    back: 'Back'
  },
  hi: {
    home: 'होम',
    shop: 'शॉप',
    menu: 'मेन्यू',
    settings: 'सेटिंग्स',
    my_uid: 'मेरी यूआईडी',
    language: 'भाषा',
    contact_support: 'सहायता से संपर्क करें',
    legal_info: 'कानूनी जानकारी',
    terms_conditions: 'नियम और शर्तें',
    privacy_policy: 'गोपनीयता नीति',
    acceptable_use: 'स्वीकार्य उपयोग नीति',
    copied: 'क्लिपबोर्ड पर कॉपी किया गया!',
    close: 'बंद करें',
    axn_balance: 'AXN बैलेंस',
    user_account: 'उपयोगकर्ता खाता',
    active: 'सक्रिय',
    user_uid: 'उपयोगकर्ता यूआईडी',
    account_localization: 'खाता और स्थानीयकरण',
    support_legal: 'सहायता और कानूनी',
    app_language: 'ऐप की भाषा',
    invite_friends: 'दोस्तों को आमंत्रित करें',
    earn_commissions: 'कमीशन कमाएं',
    watch_ads: 'विज्ञापन देखें',
    daily_reward: 'दैनिक इनाम',
    mining_status: 'माइनिंग स्थिति',
    rank: 'रैंक',
    total_axn: 'कुल AXN',
    total_usd: 'कुल USD',
    mining_power: 'माइनिंग पावर',
    earn: 'कमाएं',
    referrals: 'रेफरल',
    invite_friends_earn: 'दोस्तों को आमंत्रित करें और कमाएं',
    referral_desc_prefix: 'उनके AXN का 10% और जब आपका मित्र कोई प्लान खरीदता है तो आपको',
    referral_desc_suffix: 'तुरंत मिलते हैं',
    user_referred: 'रेफर किए गए उपयोगकर्ता',
    successful: 'सफल',
    copy_link: 'लिंक कॉपी करें',
    total_axn_mined: 'कुल AXN माइन किया गया',
    total_ton_earned: 'कुल TON कमाया गया',
    mined_axn: 'माइन किया गया AXN',
    upgrade: 'अपग्रेड',
    claim: 'दावा करें',
    convert: 'बदलें',
    promo: 'प्रोमो'
  },
  ru: {
    home: 'Главная',
    shop: 'Магазин',
    menu: 'Меню',
    settings: 'Настройки',
    my_uid: 'Мой UID',
    language: 'Язык',
    contact_support: 'Поддержка',
    legal_info: 'Юридическая информация',
    terms_conditions: 'Условия и положения',
    privacy_policy: 'Политика конфиденциальности',
    acceptable_use: 'Правила использования',
    copied: 'Скопировано!',
    close: 'Закрыть',
    axn_balance: 'Баланс AXN',
    user_account: 'Аккаунт пользователя',
    active: 'Активен',
    user_uid: 'UID пользователя',
    account_localization: 'Аккаунт и локализация',
    support_legal: 'Поддержка и закон',
    app_language: 'Язык приложения',
    invite_friends: 'Пригласить друзей',
    earn_commissions: 'Зарабатывать комиссии',
    watch_ads: 'Смотреть рекламу',
    daily_reward: 'Ежедневная награда',
    mining_status: 'Статус майнинга',
    rank: 'Ранг',
    total_axn: 'Всего AXN',
    total_usd: 'Всего USD',
    mining_power: 'Мощность майнинга'
  },
  fa: {
    home: 'خانه',
    shop: 'فروشگاه',
    menu: 'منو',
    settings: 'تنظیمات',
    my_uid: 'شناسه من',
    language: 'زبان',
    contact_support: 'تماس با پشتیبانی',
    legal_info: 'اطلاعات حقوقی',
    terms_conditions: 'شرایط و ضوابط',
    privacy_policy: 'سیاست حریم خصوصی',
    acceptable_use: 'خط‌مشی استفاده قابل قبول',
    copied: 'در حافظه کپی شد!',
    close: 'بستن',
    axn_balance: 'موجودی AXN',
    user_account: 'حساب کاربری',
    active: 'فعال',
    user_uid: 'شناسه کاربر',
    account_localization: 'حساب و بومی‌سازی',
    support_legal: 'پشتیبانی و حقوقی',
    app_language: 'زبان برنامه',
    invite_friends: 'دعوت از دوستان',
    earn_commissions: 'کسب کمیسیون',
    watch_ads: 'مشاهده تبلیغات',
    daily_reward: 'پاداش روزانه',
    mining_status: 'وضعیت استخراج',
    rank: 'رتبه',
    total_axn: 'کل AXN',
    total_usd: 'کل USD',
    mining_power: 'قدرت استخراج'
  },
  ar: {
    home: 'الرئيسية',
    shop: 'المتجر',
    menu: 'القائمة',
    settings: 'الإعدادات',
    my_uid: 'معرفي',
    language: 'اللغة',
    contact_support: 'اتصل بالدعم',
    legal_info: 'معلومات قانونية',
    terms_conditions: 'الشروط والأحكام',
    privacy_policy: 'سياسة الخصوصية',
    acceptable_use: 'سياسة الاستخدام المقبول',
    copied: 'تم النسخ إلى الحافظة!',
    close: 'إغلاق',
    axn_balance: 'رصيد AXN',
    user_account: 'حساب المستخدم',
    active: 'نشط',
    user_uid: 'معرف المستخدم',
    account_localization: 'الحساب والموقع',
    support_legal: 'الدعم والقانونية',
    app_language: 'لغة التطبيق',
    invite_friends: 'دعوة الأصدقاء',
    earn_commissions: 'كسب العمولات',
    watch_ads: 'شاهد الإعلانات',
    daily_reward: 'مكافأة يومية',
    mining_status: 'حالة التعدين',
    rank: 'الترتيب',
    total_axn: 'إجمالي AXN',
    total_usd: 'إجمالي USD',
    mining_power: 'قوة التعدين'
  },
  tr: {
    home: 'Ana Sayfa',
    shop: 'Mağaza',
    menu: 'Menü',
    settings: 'Ayarlar',
    my_uid: 'UID’im',
    language: 'Dil',
    contact_support: 'Destekle İletişime Geç',
    legal_info: 'Yasal Bilgi',
    terms_conditions: 'Şartlar ve Koşullar',
    privacy_policy: 'Gizlilik Politikası',
    acceptable_use: 'Kabul Edilebilir Kullanım Politikası',
    copied: 'Panoya kopyalandı!',
    close: 'Kapat',
    axn_balance: 'AXN Bakiyesi',
    user_account: 'Kullanıcı Hesabı',
    active: 'Aktif',
    user_uid: 'Kullanıcı UID',
    account_localization: 'Hesap ve Yerelleştirme',
    support_legal: 'Destek ve Yasal',
    app_language: 'Uygulama Dili',
    invite_friends: 'Arkadaşlarını Davet Et',
    earn_commissions: 'Komisyon Kazan',
    watch_ads: 'Reklam İzle',
    daily_reward: 'Günlük Ödül',
    mining_status: 'Madencilik Durumu',
    rank: 'Sıralama',
    total_axn: 'Toplam AXN',
    total_usd: 'Toplam USD',
    mining_power: 'Madencilik Gücü'
  },
  es: {
    home: 'Inicio',
    shop: 'Tienda',
    menu: 'Menú',
    settings: 'Ajustes',
    my_uid: 'Mi UID',
    language: 'Idioma',
    contact_support: 'Contactar Soporte',
    legal_info: 'Información Legal',
    terms_conditions: 'Términos y Condiciones',
    privacy_policy: 'Política de Privacidad',
    acceptable_use: 'Política de Uso Aceptable',
    copied: '¡Copiado al portapapeles!',
    close: 'Cerrar',
    axn_balance: 'Saldo AXN',
    user_account: 'Cuenta de Usuario',
    active: 'Activo',
    user_uid: 'UID de Usuario',
    account_localization: 'Cuenta y Localización',
    support_legal: 'Soporte y Legal',
    app_language: 'Idioma de la App',
    invite_friends: 'Invitar Amigos',
    earn_commissions: 'Ganar Comisiones',
    watch_ads: 'Ver Anuncios',
    daily_reward: 'Recompensa Diaria',
    mining_status: 'Estado de Minería',
    rank: 'Rango',
    total_axn: 'Total AXN',
    total_usd: 'Total USD',
    mining_power: 'Poder de Minería'
  },
  pt: {
    home: 'Início',
    shop: 'Loja',
    menu: 'Menu',
    settings: 'Configurações',
    my_uid: 'Meu UID',
    language: 'Idioma',
    contact_support: 'Contatar Suporte',
    legal_info: 'Informação Legal',
    terms_conditions: 'Termos e Condições',
    privacy_policy: 'Política de Privacidade',
    acceptable_use: 'Política de Uso Aceitável',
    copied: 'Copiado para a área de transferência!',
    close: 'Fechar',
    axn_balance: 'Saldo AXN',
    user_account: 'Conta de Usuário',
    active: 'Ativo',
    user_uid: 'UID de Usuário',
    account_localization: 'Conta e Localização',
    support_legal: 'Suporte e Legal',
    app_language: 'Idioma do App',
    invite_friends: 'Convidar Amigos',
    earn_commissions: 'Ganhar Comissões',
    watch_ads: 'Assistir Anúncios',
    daily_reward: 'Recompensa Diária',
    mining_status: 'Status da Mineração',
    rank: 'Classificação',
    total_axn: 'Total AXN',
    total_usd: 'Total USD',
    mining_power: 'Poder de Mineração'
  },
  id: {
    home: 'Beranda',
    shop: 'Toko',
    menu: 'Menu',
    settings: 'Pengaturan',
    my_uid: 'UID Saya',
    language: 'Bahasa',
    contact_support: 'Hubungi Dukungan',
    legal_info: 'Informasi Hukum',
    terms_conditions: 'Syarat & Ketentuan',
    privacy_policy: 'Kebijakan Privasi',
    acceptable_use: 'Kebijakan Penggunaan',
    copied: 'Disalin ke papan klip!',
    close: 'Tutup',
    axn_balance: 'Saldo AXN',
    user_account: 'Akun Pengguna',
    active: 'Aktif',
    user_uid: 'UID Pengguna',
    account_localization: 'Akun & Lokalisasi',
    support_legal: 'Dukungan & Hukum',
    app_language: 'Bahasa Aplikasi',
    invite_friends: 'Undang Teman',
    earn_commissions: 'Dapatkan Komisi',
    watch_ads: 'Tonton Iklan',
    daily_reward: 'Hadiah Harian',
    mining_status: 'Status Penambangan',
    rank: 'Peringkat',
    total_axn: 'Total AXN',
    total_usd: 'Total USD',
    mining_power: 'Kekuatan Penambangan'
  },
  ur: {
    home: 'ہوم',
    shop: 'شاپ',
    menu: 'مینیو',
    settings: 'ترتیبات',
    my_uid: 'میری UID',
    language: 'زبان',
    contact_support: 'سپورٹ سے رابطہ کریں',
    legal_info: 'قانونی معلومات',
    terms_conditions: 'شرائط و ضوابط',
    privacy_policy: 'رازداری کی پالیسی',
    acceptable_use: 'قابل قبول استعمال کی پالیسی',
    copied: 'کلپ بورڈ پر کاپی ہو گیا!',
    close: 'بند کریں',
    axn_balance: 'AXN بیلنس',
    user_account: 'صارف کا اکاؤنٹ',
    active: 'فعال',
    user_uid: 'صارف کی UID',
    account_localization: 'اکاؤنٹ اور مقام',
    support_legal: 'سپورٹ اور قانونی',
    app_language: 'ایپ کی زبان',
    invite_friends: 'دوستوں کو مدعو کریں',
    earn_commissions: 'کمیشن کمائیں',
    watch_ads: 'اشتہارات دیکھیں',
    daily_reward: 'روزانہ انعام',
    mining_status: 'مائننگ کی صورتحال',
    rank: 'رینک',
    total_axn: 'کل AXN',
    total_usd: 'کل USD',
    mining_power: 'مائننگ پاور'
  },
  bn: {
    home: 'হোম',
    shop: 'শপ',
    menu: 'মেনু',
    settings: 'সেটিংস',
    my_uid: 'আমার UID',
    language: 'ভাষা',
    contact_support: 'সাপোর্টে যোগাযোগ করুন',
    legal_info: 'আইনি তথ্য',
    terms_conditions: 'শর্তাবলী',
    privacy_policy: 'গোপনীয়তা নীতি',
    acceptable_use: 'ব্যবহারের নীতি',
    copied: 'ক্লিপবোর্ডে কপি করা হয়েছে!',
    close: 'বন্ধ করুন',
    axn_balance: 'AXN ব্যালেন্স',
    user_account: 'ব্যবহারকারী অ্যাকাউন্ট',
    active: 'সক্রিয়',
    user_uid: 'ব্যবহারকারী UID',
    account_localization: 'অ্যাকাউন্ট এবং লোকালাইজেশন',
    support_legal: 'সাপোর্ট এবং আইনি',
    app_language: 'অ্যাপের ভাষা',
    invite_friends: 'বন্ধুদের আমন্ত্রণ জানান',
    earn_commissions: 'কমিশন অর্জন করুন',
    watch_ads: 'বিজ্ঞাপন দেখুন',
    daily_reward: 'দৈনিক পুরস্কার',
    mining_status: 'মাইনিং স্ট্যাটাস',
    rank: 'র‌্যাঙ্ক',
    total_axn: 'মোট AXN',
    total_usd: 'মোট USD',
    mining_power: 'মাইনিং পাওয়ার'
  },
  fr: {
    home: 'Accueil',
    shop: 'Boutique',
    menu: 'Menu',
    settings: 'Paramètres',
    my_uid: 'Mon UID',
    language: 'Langue',
    contact_support: 'Contacter le Support',
    legal_info: 'Informations Légales',
    terms_conditions: 'Termes et Conditions',
    privacy_policy: 'Politique de Confidentialité',
    acceptable_use: 'Politique d\'Utilisation',
    copied: 'Copié dans le presse-papiers !',
    close: 'Fermer',
    axn_balance: 'Solde AXN',
    user_account: 'Compte Utilisateur',
    active: 'Actif',
    user_uid: 'UID Utilisateur',
    account_localization: 'Compte et Localisation',
    support_legal: 'Support et Légal',
    app_language: 'Langue de l\'App',
    invite_friends: 'Inviter des Amis',
    earn_commissions: 'Gagner des Commissions',
    watch_ads: 'Regarder des Pubs',
    daily_reward: 'Récompense Quotidienne',
    mining_status: 'Statut du Minage',
    rank: 'Rang',
    total_axn: 'Total AXN',
    total_usd: 'Total USD',
    mining_power: 'Puissance de Minage'
  },
  de: {
    home: 'Start',
    shop: 'Shop',
    menu: 'Menü',
    settings: 'Einstellungen',
    my_uid: 'Meine UID',
    language: 'Sprache',
    contact_support: 'Support kontaktieren',
    legal_info: 'Rechtliche Informationen',
    terms_conditions: 'AGB',
    privacy_policy: 'Datenschutz',
    acceptable_use: 'Nutzungsbedingungen',
    copied: 'In die Zwischenablage kopiert!',
    close: 'Schließen',
    axn_balance: 'AXN Guthaben',
    user_account: 'Benutzerkonto',
    active: 'Aktiv',
    user_uid: 'Benutzer UID',
    account_localization: 'Konto & Lokalisierung',
    support_legal: 'Support & Rechtliches',
    app_language: 'App-Sprache',
    invite_friends: 'Freunde einladen',
    earn_commissions: 'Provisionen verdienen',
    watch_ads: 'Werbung ansehen',
    daily_reward: 'Tägliche Belohnung',
    mining_status: 'Mining-Status',
    rank: 'Rang',
    total_axn: 'Gesamt AXN',
    total_usd: 'Gesamt USD',
    mining_power: 'Mining-Leistung'
  },
  it: {
    home: 'Home',
    shop: 'Negozio',
    menu: 'Menu',
    settings: 'Impostazioni',
    my_uid: 'Mio UID',
    language: 'Lingua',
    contact_support: 'Contatta Supporto',
    legal_info: 'Informazioni Legali',
    terms_conditions: 'Termini e Condizioni',
    privacy_policy: 'Privacy Policy',
    acceptable_use: 'Politica di Utilizzo',
    copied: 'Copiato negli appunti!',
    close: 'Chiudi',
    axn_balance: 'Saldo AXN',
    user_account: 'Account Utente',
    active: 'Attivo',
    user_uid: 'UID Utente',
    account_localization: 'Account e Localizzazione',
    support_legal: 'Supporto e Legale',
    app_language: 'Lingua dell\'App',
    invite_friends: 'Invita Amici',
    earn_commissions: 'Guadagna Commissioni',
    watch_ads: 'Guarda Annunci',
    daily_reward: 'Premio Giornaliero',
    mining_status: 'Stato Mining',
    rank: 'Grado',
    total_axn: 'Totale AXN',
    total_usd: 'Totale USD',
    mining_power: 'Potenza Mining'
  },
  zh: {
    home: '首页',
    shop: '商店',
    menu: '菜单',
    settings: '设置',
    my_uid: '我的 UID',
    language: '语言',
    contact_support: '联系支持',
    legal_info: '法律信息',
    terms_conditions: '条款和条件',
    privacy_policy: '隐私政策',
    acceptable_use: '可接受使用政策',
    copied: '已复制到剪贴板！',
    close: '关闭',
    axn_balance: 'AXN 余额',
    user_account: '用户账户',
    active: '活跃',
    user_uid: '用户 UID',
    account_localization: '账户和本地化',
    support_legal: '支持和法律',
    app_language: '应用语言',
    invite_friends: '邀请好友',
    earn_commissions: '赚取佣金',
    watch_ads: '观看广告',
    daily_reward: '每日奖励',
    mining_status: '挖矿状态',
    rank: '排名',
    total_axn: '总 AXN',
    total_usd: '总 USD',
    mining_power: '挖矿算力'
  },
  ja: {
    home: 'ホーム',
    shop: 'ショップ',
    menu: 'メニュー',
    settings: '設定',
    my_uid: '私のUID',
    language: '言語',
    contact_support: 'サポートに連絡',
    legal_info: '法的情報',
    terms_conditions: '利用規約',
    privacy_policy: 'プライバシーポリシー',
    acceptable_use: '利用規定',
    copied: 'クリップボードにコピーしました！',
    close: '閉じる',
    axn_balance: 'AXN残高',
    user_account: 'ユーザーアカウント',
    active: 'アクティブ',
    user_uid: 'ユーザーUID',
    account_localization: 'アカウントとローカライズ',
    support_legal: 'サポートと法務',
    app_language: 'アプリの言語',
    invite_friends: '友達を招待',
    earn_commissions: 'コミッションを獲得',
    watch_ads: '広告を見る',
    daily_reward: 'デイリー報酬',
    mining_status: 'マイニング状況',
    rank: 'ランク',
    total_axn: '合計 AXN',
    total_usd: '合計 USD',
    mining_power: 'マイニングパワー'
  },
  ko: {
    home: '홈',
    shop: '상점',
    menu: '메뉴',
    settings: '설정',
    my_uid: '나의 UID',
    language: '언어',
    contact_support: '고객 지원',
    legal_info: '법적 정보',
    terms_conditions: '이용 약관',
    privacy_policy: '개인정보 처리방침',
    acceptable_use: '이용 정책',
    copied: '클립보드에 복사되었습니다!',
    close: '닫기',
    axn_balance: 'AXN 잔액',
    user_account: '사용자 계정',
    active: '활성',
    user_uid: '사용자 UID',
    account_localization: '계정 및 현지화',
    support_legal: '지원 및 법률',
    app_language: '앱 언어',
    invite_friends: '친구 초대',
    earn_commissions: '커미션 적립',
    watch_ads: '광고 시청',
    daily_reward: '일일 보상',
    mining_status: '채굴 상태',
    rank: '순위',
    total_axn: '총 AXN',
    total_usd: '총 USD',
    mining_power: '채굴 파워'
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    return (saved as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('app_language', lang);
  };

  const t = (key: string) => {
    const currentTranslations = translations[language] || translations['en'];
    return currentTranslations[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};